name: Build JAR

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build Maven project
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '8'
          cache: maven

      - name: Build JAR
        run: mvn -B -ntp package -DskipTests
