name: Build JAR

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build Maven project
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build JAR
        run: mvn -B -ntp package

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: speechdrop-jar
          path: target/*.jar
          if-no-files-found: error
